version: '3.9'

services:
  postgres:
    image: postgres
    platform: linux/amd64
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jod-jod
    ports:
      - '5432:5432'

  redis:
    image: redis
    platform: linux/amd64
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command:
      - redis-server /redis.conf
